{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
{{- $namespace := $.Release.Namespace -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: anchore-policyengine-policy
  namespace: {{ $namespace }}
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: 
        - "8087"
{{- end }}