{{- if hasKey .Values.postgresql "enabled" }}
{{- if (not .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: anchore-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anchore-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  PGUSER: {{ .Values.postgresql.postgresUser | quote }}
  {{- if (not .Values.global.existingSecret) }}
  PGPASSWORD: {{ .Values.postgresql.postgresPassword | quote }}
  {{- end }}
  PGDATABASE: {{ "postgres" | quote }}
  PGHOST: {{ .Values.postgresql.externalEndpoint | quote }}
  PGPORT: {{ .Values.postgresql.postgresPort | quote }}
  ANCHORE_DB: {{ .Values.postgresql.postgresDatabase | quote }}
{{- end }}
{{- end }}
