{{- if hasKey .Values.postgresql "enabled" }}
{{- if (not .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: anchore-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anchore-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore-enterprise
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  PGUSER: {{ b64enc .Values.postgresql.postgresUser }}
  {{- if (not .Values.anchoreGlobal.existingSecret) }}
  PGPASSWORD: {{ b64enc .Values.postgresql.postgresPassword }}
  {{- end }}
  PGDATABASE: {{ b64enc "postgres" }}
  PGHOST: {{ b64enc .Values.postgresql.externalEndpoint }}
  PGPORT: "{{ b64enc .Values.postgresql.postgresPort }}"
  ANCHORE_DB: {{ b64enc .Values.postgresql.postgresDatabase }}
{{- end }}
{{- end }}
