{{- if (hasKey (index .Values "anchore-feeds-db") "enabled") }}
{{- if (not (index .Values "anchore-feeds-db" "enabled")) }}
apiVersion: v1
kind: Secret
metadata:
  name: feeds-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: feeds-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  PGUSER: {{ (index .Values "anchore-feeds-db" "postgresUser") | quote }}
  {{- if (not .Values.feeds.existingSecret) }}
  PGPASSWORD: {{ (index .Values "anchore-feeds-db" "postgresPassword") | quote}}
  {{- end }}
  PGDATABASE: {{ "postgres" | quote }}
  PGHOST: {{ (index .Values "anchore-feeds-db" "externalEndpoint") | quote }}
  PGPORT: {{ (index .Values "anchore-feeds-db" "postgresPort") | quote }}
  FEEDS_DB: {{ (index .Values "anchore-feeds-db" "postgresDatabase") | quote }}
{{- end }}
{{- end }}
