{{- if and .Values.postgresqlSuperUser.postgresUsername .Values.postgresqlSuperUser.postgresPassword }}
{{- if (not .Values.postgresqlSuperUser.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: superuser-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: superuser-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  PGUSER: {{ .Values.postgresqlSuperUser.postgresUsername | quote }}
  PGPASSWORD: {{ .Values.postgresqlSuperUser.postgresPassword | quote }}
  PGDATABASE: {{ "postgres" | quote }}
  PGHOST: {{ .Values.postgresql.externalEndpoint | quote }}
  PGPORT: {{ .Values.postgresql.postgresPort | quote }}
  ANCHORE_DB: {{ .Values.postgresql.postgresDatabase | quote }}
{{- end }}
{{- end }}
