{{- if and .Values.postgresqlSuperUser.postgresUsername .Values.postgresqlSuperUser.postgresPassword }}
{{- if (not .Values.postgresqlSuperUser.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: superuser-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: superuser-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore-enterprise
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  PGUSER: {{ b64enc .Values.postgresqlSuperUser.postgresUsername }}
  PGPASSWORD: {{ b64enc .Values.postgresqlSuperUser.postgresPassword }}
  PGDATABASE: {{ b64enc "postgres" }}
  PGHOST: {{ .Values.postgresql.externalEndpoint }}
  PGPORT: "{{ .Values.postgresql.postgresPort }}"
  ANCHORE_DB: {{ b64enc .Values.postgresql.postgresDatabase }}
{{- end }}
{{- end }}
