{{- /* Adds additional anchore-enterprise policies based on values */ -}}
{{- if .Values.networkPolicies.enabled }}
{{- range $policy := .Values.networkPolicies.additionalPolicies -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $policy.name }}
spec:
  {{- toYaml $policy.spec | nindent 2 }}
---
{{- end }}
{{- end }}
