{{- if and .Values.sso.enabled .Values.anchoreEnterpriseGlobal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: anchore-sso
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sso-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore-enterprise
    app.kubernetes.io/component: sso
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
stringData:
  {{ with .Values.sso }}
  anchore-sso.json: |-
    {
      "name": "{{ .name }}",
      "enabled": {{ .enabled }},
      "acs_https_port": {{ .acsHttpsPort }},
      "sp_entity_id": "{{ .spEntityId }}",
      "acs_url": "{{ .acsUrl }}",
      "default_account": "{{ .defaultAccount }}",
      {{- if .roleAttribute }}
      "idp_role_attribute": "{{ .roleAttribute }}",
      {{- else if .defaultRole }}
      "default_role": "{{ .defaultRole }}",
      {{- end }}
      "require_signed_assertions": {{ .requireSignedAssertions }},
      "require_signed_response": {{ .requireSignedResponse }},
      "idp_metadata_url": "{{ .idpMetadataUrl }}"
    }
  {{- end }}
{{- end }}
