{{- /* Render Istio ServiceEntry for SSO */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled (gt (len .Values.feedsHosts) 0) -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: anchore-feeds-service-entry
  namespace: {{ .Release.Namespace }}
spec:
  exportTo:
    - "."
  hosts:
  {{- range .Values.feedsHosts }}
  - {{ . -}}
  {{ end }}
  location: MESH_EXTERNAL
  ports:
    - number: 443
      protocol: TLS
      name: https
{{- end -}}
