{{- /* Render Istio ServiceEntry for anchore policy toolbox data */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: toolbox-data-service-entry
  namespace: {{ .Release.Namespace }}
spec:
  exportTo:
    - "."
  hosts:
    - "toolbox-data.anchore.io"
  location: MESH_EXTERNAL
  ports:
    - number: 443
      protocol: TLS
      name: https
{{- end -}}
