{{- $component := "certs" -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: anchore-certs
  labels:
    app: {{ template "anchore.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $component }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "anchore.gen-certs" . ) | indent 2 }}
