{{- if and .Values.anchoreEnterpriseGlobal.enabled (or .Values.enterpriseLicense.yaml .Values.enterpriseLicense.b64encYaml) }}
apiVersion: v1
kind: Secret
metadata:
  name: anchore-enterprise-license
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anchore-enterprise-license
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore-enterprise
    app.kubernetes.io/component: license
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  {{- if .Values.enterpriseLicense.yaml }}
  license.yaml: {{ .Values.enterpriseLicense.yaml | b64enc }}
  {{- end }}
  {{- if .Values.enterpriseLicense.b64encYaml }}
  license.yaml: {{ .Values.enterpriseLicense.b64encYaml }}
  {{- end }}
{{- end }}