{{- if and .Values.anchoreEnterpriseGlobal.enabled .Values.enterpriseLicenseYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: anchore-enterprise-license
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anchore-enterprise-license
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore-enterprise
    app.kubernetes.io/component: license
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  license.yaml: {{ .Values.enterpriseLicenseYaml | b64enc }}
{{- end }}