{{- /* Render Istio ServiceEntry for anchore datasync */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: data-anchore-service-entry
  namespace: {{ .Release.Namespace }}
spec:
  exportTo:
    - "."
  hosts:
    - "data.anchore-enterprise.com"
  location: MESH_EXTERNAL
  ports:
    - number: 443
      protocol: TLS
      name: https
{{- end -}}
