{{- if and (eq .Values.istio.injection "enabled") .Values.istio.enabled .Values.monitoring.enabled (eq .Values.istio.mtls.mode "STRICT") .Values.anchoreEnterpriseGlobal.enabled }}
{{- if .Values.anchoreEnterpriseFeeds.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: anchore-feeds-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      component: "enterprise-feeds"
  portLevelMtls:
    "{{ .Values.anchoreEnterpriseFeeds.service.port }}":
      mode: PERMISSIVE
{{- end }}
{{- if .Values.anchoreEnterpriseRbac.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: anchore-rbac-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      component: "enterprise-rbac"
  portLevelMtls:
    "{{ .Values.anchoreEnterpriseRbac.service.managerPort }}":
      mode: PERMISSIVE
{{- end }}
{{- if .Values.anchoreEnterpriseReports.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: anchore-reports-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      component: "enterprise-reports"
  portLevelMtls:
    "{{ .Values.anchoreEnterpriseReports.service.workerPort }}":
      mode: PERMISSIVE
{{- end }}
{{- if .Values.anchoreEnterpriseNotifications.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: anchore-notifications-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      component: "enterprise-notifications"
  portLevelMtls:
    "{{ .Values.anchoreEnterpriseNotifications.service.port }}":
      mode: PERMISSIVE
{{- end }}
{{- end }}
