{{- if and (eq .Values.istio.injection "enabled") .Values.istio.enabled .Values.monitoring.enabled (eq .Values.istio.mtls.mode "STRICT") }}
{{- if and .Values.anchoreEnterpriseGlobal.enabled (not (hasKey (index .Values "anchore-ui-redis") "enabled")) }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: anchore-redis-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app.kubernetes.io/name: anchore-ui-redis
  portLevelMtls:
    "9121":
      mode: PERMISSIVE
{{- end }}
{{- end }}
