apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJSON6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: anchore-anchore-engine-enterprise-ui
    path: patch.ui-istio.yaml
